USE gram_panchayat_db;
SHOW TABLES;

SELECT UPPER(FULL_NAME) FROM CITIZEN;
SELECT LOWER(VILLAGE_NAME) FROM CITIZEN;
SELECT LENGTH(FULL_NAME) FROM CITIZEN;
SELECT CONCAT(FULL_NAME," - ",VILLAGE_NAME) FROM CITIZEN;
SELECT LEFT(REFERENCE_NUMBER,4) FROM  CERTIFICATE_APPLICATION;


SELECT REPLACE(CERTIFICATE_NAME, "Certificate",'Cert.') FROM CERTIFICATE_TYPE;
SELECT TRIM(CERTIFICATE_NAME) FROM  CERTIFICATE_TYPE;
SELECT SUBSTRING_INDEX(FULL_NAME,' ',1) AS FIRST_NAME FROM  CITIZEN;

SELECT CONCAT("Citizen : ", full_name , '\n','Village : ', village_name) FROM CITIZEN;
SELECT * FROM CERTIFICATE_APPLICATION WHERE LEFT(REFERENCE_NUMBER,6) LIKE "GP2026";

SELECT ROUND(APPLICATION_FEE) FROM CERTIFICATE_TYPE;
SELECT ABS(PROCESSING_DAYS-10) FROM CERTIFICATE_TYPE;
SELECT POWER(PROCESSING_DAYS,2) FROM CERTIFICATE_TYPE;

SELECT MOD(PROCESSING_DAYS,3) FROM CERTIFICATE_TYPE;
SELECT ROUND(APPLICATION_FEE,1) FROM CERTIFICATE_TYPE;
SELECT CEIL(APPLICATION_FEE),FLOOR(APPLICATION_FEE) FROM CERTIFICATE_TYPE;
SELECT FLOOR(RAND() * 100 + 1) FROM CERTIFICATE_TYPE;











SELECT * FROM Citizen;
SELECT * FROM Certificate_Type;
SELECT * FROM Certificate_Application;
SELECT * FROM Panchayat_Office;
